version: "3"

services: 

  db:
    image: mysql:5.7
    container_name: mysql
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./mysql-files:/var/lib/mysql 
    restart: always    
    environment: 
      - MYSQL_ROOT_PASSWORD=mestre
      - MYSQL_DATABASE=teste      

    networks: 
      - net-node
    ports: 
      - 3306:3306

networks: 
  net-node:
    driver: bridge  