version: "3"

services: 

  db:
    build: 
      context: .
      dockerfile: Dockerfile.mysql    
    container_name: mysql
    tty: true
    command: --default-authentication-plugin=mysql_native_password  
    restart: always    
    environment: 
      - MYSQL_ROOT_PASSWORD=mestre
      - MYSQL_DATABASE=teste      

    networks: 
      - net-node
  
  node-app:
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: node-app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s node index.js
    tty: true
    restart: always
    depends_on: 
      - db
    networks: 
      - net-node  

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx    
    restart: always
    tty: true
    depends_on: 
      - node-app
    ports: 
      - 8080:80
    networks: 
      - net-node

networks: 
  net-node:
    driver: bridge  